# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool: mylapu

#/plainjanetypes/vnetcheck/M01-VDES-03-ER-ddos

steps:
- script: |
   cd $(Build.SourcesDirectory)/networksetup/M01-VDES-03-ER-ddos
   terraform init
   terraform plan
  displayName: 'terraform plan'

