# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool: mylapu

steps:
- script: |
    
    terraform init 2>&1
  displayName: 'TF init'
  workingDirectory: 'C:\agent\_work\8\s\M01-VDES-03-ER-ddos'

- script: |

    terraform plan
  displayName: 'TF plan'
  workingDirectory: 'C:\agent\_work\8\s\M01-VDES-03-ER-ddos'

# resources:
#  repositories:
#     - repository: vnetcheck
#       type: github
#       endpoint: pj-hub
#       name: plainjanetypes/vnetcheck
#       path: M01-VDES-03-ER-ddos
#       ref: main


#/plainjanetypes/vnetcheck/M01-VDES-03-ER-ddos
#cd $(Build.SourcesDirectory)/networksetup/M01-VDES-03-ER-ddos and cd $(Build.SourcesDirectory) didnt work
#- checkout: self


# - script: |
#     echo "current working directory : $(System.DefaultWorkingDirectory) and $(Build.SourcesDirectory)/subdirectory"
#   displayName: 'working directory'

# - script: |
#       echo "Local path of Git repository: $(Build.Repository.LocalPath)"
#   displayName: 'Print Git Repository Local Path'

# - script: |
#    echo "current working directory : $(System.DefaultWorkingDirectory)"
#    cd $(System.DefaultWorkingDirectory)/vnetcheck/M01-VDES-03-ER-ddos
#    terraform init
#    terraform plan
#   displayName: 'terraform plan'







