# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool: mylapu

resources:
 repositories:
    - repository: vnetcheck
      type: azureRepo
      name: networkingaz700/networksetup
      ref: refs/heads/M01-VDES-03-ER-ddos
      

#/plainjanetypes/vnetcheck/M01-VDES-03-ER-ddos
#cd $(Build.SourcesDirectory)/networksetup/M01-VDES-03-ER-ddos and cd $(Build.SourcesDirectory) didnt work

steps:
- script: |
   
   terraform init
   terraform plan
  displayName: 'terraform plan'

