# for M04-LBTM

#set trigger to none/manual
trigger: none
#  branches:
#    include:
#      - main

pool: mylapu

steps:
- script: |
    echo 'terraform init'
    terraform init 2>&1
  displayName: 'terraform init'
  workingDirectory: 'C:\agent\_work\1\s'

- script: |
    echo 'publish terraform plan'
    terraform plan
  displayName: 'terraform plan'
  workingDirectory: 'C:\agent\_work\1\s'