#for M06-FWALL
# Starter pipeline


trigger:
  branches:
    include:
      - main

pool: mylapu

steps:
- script: |
    echo 'terraform init'
    terraform init
  displayName: 'terraform init'
  workingDirectory: 'C:\agent\_work\1\s'

- script: |
    echo 'publish terraform plan'
    terraform plan
  displayName: 'terraform plan'
  workingDirectory: 'C:\agent\_work\1\s'
